name: dart_sodium
description: A starting point for Dart libraries or applications.
version: 2.0.0-dev
homepage: https://www.example.com

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  ffi_helper: ^1.0.0
  ffi: ^0.1.3
  meta: ^1.1.8

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  benchmark_harness: ^1.0.5