name: dart_sodium
description: FFI bindings for the libsodium cryptographic library. 
  Libsodium is a robust and well reviewed collection of high- and low-level functions for many kinds of 
  cryptographic use cases.
version: 1.0.0
homepage: https://gitlab.com/MagicGuitar/dart-sodium
repository: https://gitlab.com/MagicGuitar/dart-sodium
author: Marvin Hannott <marvinhannott@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
