name: dart_sodium
description: FFI bindings for libsodium
version: 0.1.0
repository: https://gitlab.com/MagicGuitar/dart-sodium
author: Marvin Hannott <marvinhannott@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
